config/routes.rb
Fft::Application.routes.draw do

  devise_for :users
  resources :users, only: [:index, :destroy]

  resources :games do
    member do
      post :rate
    end
  end
  
  resources :categories
  resources :comments, only: [:create, :destroy]
  
  root to: "static_pages#home"
  
  match "/help",    to: "static_pages#help"
  match "/about",   to: "static_pages#about"
  match "/contact", to: "static_pages#contact"
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :games
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :game_id
  
  belongs_to :user
  belongs_to :game
  
  validates :user_id, presence: true
  validates :game_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  
  default_scope order: 'comments.created_at DESC'
end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :name, :instructions, :description
  
  belongs_to :category
  
  has_many :comments
  
  has_many :users, :through => :comments
  
  ajaxful_rateable :allow_update => true, :stars => 5
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
  validates_numericality_of :stars, :minimum => 1
  
  attr_accessible :rate, :dimension
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :username, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  validates_presence_of :username
  validates_uniqueness_of :username
  
  has_many :comments, dependent: :destroy
  
  has_many :games, through:  :comments
  
  ajaxful_rater dependent:  :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end
  
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @games = @category.games.paginate(page: params[:page], per_page: 18)    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(params[:comment])
    if @comment.save
      redirect_to game_url(id: @comment.game.id)
    else
      redirect_to root_url
    end
  end
  
  def destroy
    Comment.find(params[:id]).destroy
    redirect_to :back
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = Game.paginate(page: params[:page], per_page: 18)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])
    @games = Game.all
    @comment = current_user.comments.build if current_user
    @comments = @game.comments.paginate(page: params[:page], per_page: 8)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end
  
  def rate
    @game = Game.find(params[:id])
    @game.rate(params[:stars], current_user, params[:dimension])
    respond_to do |format|
      format.js
    end
  end

  def update
    @game = Game.find(params[:id])
    if @game.update_attributes(params[:game])
        redirect_to @game
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @games = Game.all
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def destroy
  	User.find(params[:id]).destroy
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Flash Fairy Tale"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/_gamelist.html.erb
<li>
	<div class="li-img">
		<%= link_to image_tag(game.name + ".jpg"), Game.find_by_name(game.name) %>
	</div>
	<div class="li-text">
		<h4 class="li-head"><%= link_to game.name.gsub('-',' '), Game.find_by_name(game.name) %></h4>	
		Rating: <%= game.rate_average.round(2).to_s.sub(".0","") %>/5
	</div>
</li>

app/views/categories/action.html.erb
<h1>Categories#action</h1>

<p>Find me in app/views/categories/action.html.erb</p>

<% if @category.games.any? %>
	
<% end %>

app/views/categories/adventure.html.erb
<h1>Categories#adventure</h1>
<p>Find me in app/views/categories/adventure.html.erb</p>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
<% end %>
</table>

app/views/categories/music.html.erb
<h1>Categories#music</h1>
<p>Find me in app/views/categories/music.html.erb</p>

app/views/categories/puzzle.html.erb
<h1>Categories#puzzle</h1>
<p>Find me in app/views/categories/puzzle.html.erb</p>

app/views/categories/shooting.html.erb
<h1>Categories#shooting</h1>
<p>Find me in app/views/categories/shooting.html.erb</p>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<% if @category.games.any? %>
	<ul class = "gamelist">	
	<% @games.each do |game| %>
		<%= render :partial => "categories/gamelist", :locals => {:game => game} %>
	<% end %>
	</ul>
	<div class="clear"></div>
	<%= will_paginate @games%>
<% end %>

app/views/categories/sports.html.erb
<h1>Categories#sports</h1>
<p>Find me in app/views/categories/sports.html.erb</p>
	<%= link_to image_tag(@category.games.first.name + ".jpg"), Game.find_by_name(@category.games.first.name) %>
	<%= image_tag("four-second-frenzy-14.jpg") %>

app/views/categories/strategy.html.erb
<h1>Categories#strategy</h1>

<p>Find me in app/views/categories/strategy.html.erb</p>

<% path = "images/#{Category.first.name.downcase}/#{Category.first.games.first.name}.jpg"%>
<%= image_tag(path) %>
<%= image_tag("argentburst.jpg") %>
<%= image_tag("four-second-frenzy-14.jpg") %>
<%= image_tag("indestruc2tank-28.gif") %>
<p>
	sdfsd
</p>
<%= path %>

app/views/games/_admingameinfo.html.erb
<div class="admingameinfo">
	<%= form_for(@game) do |f|%>
		<div class="field">
			<%= f.text_area :description, url: { action: "update" }, html: { method: 'put' } , placeholder: "Add description", size: "20x3" %>
		</div>
		<%= f.submit "Submit description", class: "btn pull-right" %>
	<% end %>
</div>

<div class="admingameinfo">
	<%= form_for(@game) do |f|%>
		<div class="field">
			<%= f.text_area :instructions, url: { action: "update" }, html: { method: 'put' }, placeholder: "Add instructions", size: "20x3" %>
		</div>
		<%= f.submit "Submit instructions", class: "btn pull-right" %>
	<% end %>
</div>

app/views/games/_comment.html.erb
<li>
	<div class="timestamp">
		<%= comment.user.username %> posted <%= time_ago_in_words(comment.created_at) %> ago.
		<% if current_user.admin?  %>
			| <%= link_to "delete", comment, method: :delete %>
		<% end %>
	</div>
	<div class="content">
		<%= comment.content %>
	</div>
</li>

app/views/games/index.html.erb
<h2>All Games</h2>

<% if @games.any? %>
	<ul class = "gamelist">	
	<% @games.each do |game| %>
		<%= render :partial => "categories/gamelist", :locals => {:game => game} %>
	<% end %>
	</ul>
	<div class="clear"></div>
	<%= will_paginate @games %>
<% end %>

app/views/games/show.html.erb
<div class="row-fluid">
	<div class="span2">
	</div>
	<div class="span8 game">
		<embed src="<%= asset_path(@game.name + '.swf') %>", width = "640px", height = "480px">
	</div>
</div>
<% if user_signed_in?  %>
	<div class="row-fluid">
		<div class="span6">
			<h2>Feedback</h2>
			<section>
						<%= render 'shared/comment_form' %>
				</section>
				<% if @game.comments.any? %>
				<ul class="comments">
					<% @comments.each do |comment| %>
						<%= render :partial => "games/comment", :locals => {:comment => comment} %>
					<% end %>
				</ul>
				<%= will_paginate @comments %>
			<% end %>
		</div>
		<div class="span6">
			<h2>Game Info</h2>
			<h3>Description</h3>
			<div class="description"><%= @game.description %></div>
			<h3>Instructions</h3>
			<div class="instructions"><%= @game.instructions %></div>
			<h2>Rating</h2>
			Your rating: <%= ratings_for @game, :show_user_rating => true %> Overall rating: <%= ratings_for @game, :static %>
		</div>
	</div>
<% if current_user.try(:admin?) %>
	<%= render "games/admingameinfo" %>
<% end %>
<% else %>
	You must be <%= link_to "Logged in", new_user_session_path %> to post a comment, view game info and rating.
<% end %>

app/views/layouts/_footer.html.erb
<div class="clear"></div>
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
  		<div class="container">
  			<%= link_to "Flash Fairy Tale", root_path, id: "logo" %>
  			<nav>
  		    	<ul class="nav pull-right">
              <% if current_user.try(:admin?) %>
                <li><%= link_to "Users", users_path %></li>
              <% end %>   
    					<li><%= button_to "Home", root_path, :method => "get", class: "btn btn-info btnform" %></li>
    					<% if user_signed_in? %> 	
                <li>
                  <div class="btn-group">
                    <a class="btn dropdown-toggle btn-success" data-toggle="dropdown" href="#">
                      <%= current_user.username %>
                      <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Change Password", edit_user_registration_path %></li>
                      <li class="divider"></li>
                      <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
                    </ul>
                  </div>
                </li>			
    					<% else %>
    						<li><%= button_to "Sign Up", new_user_registration_path, :method => "get", class: "btn btn-warning btnform" %></li>
    						<li><%= button_to "Sign In", new_user_session_path, :method => "get", class: "btn btn-primary btnform" %></li>						
    					<% end %>
  		  		</ul>
  			</nav>
  	  </div>
	</div>
</header>

app/views/layouts/_navbar.html.erb
<div class="container menu">
	<div class="navbar">
		<div class="navbar-inner">
			<ul class="nav">
				<li><%= link_to "All games", games_path %></li>
				<li><%= link_to "Action", category_path(5) %></li>
				<li><%= link_to "Adventure & RPG", category_path(6) %></li>
				<li><%= link_to "Misc", category_path(7) %></li>
				<li><%= link_to "Music", category_path(8) %></li>
				<li><%= link_to "Puzzle", category_path(9) %></li>
				<li><%= link_to "Shooting", category_path(10) %></li>
				<li><%= link_to "Sports & Racing", category_path(11) %></li>
				<li><%= link_to "Strategy & Defense", category_path(12) %></li>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= ajaxful_rating_style %>
</head>
<body>
  <%= render "layouts/header" %>
  <%= render "layouts/navbar" %>
  <div class="container"> 	
  	<%= yield %>
  	<%= render "layouts/footer" %>
  </div>
  
</body>
</html>

app/views/shared/_comment_form.html.erb
<%= form_for(@comment) do |f|%>
	<div class="field">
		<%= f.text_area :content, placeholder: "Add your comment about the game!", size: "20x2" %>
	</div>
	
	<%= f.hidden_field :game_id, { :value => @game.id } %>
	
	<%= f.submit "Submit Comment", class: "btn pull-right" %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>...</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>...</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>...</p>

app/views/static_pages/home.html.erb
<div class="center mainContent">
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span6">
				<h3>New Games</h3>
				<% if @games.any? %>
					<ul class = "newgames">	
					<% @games.reverse[0..11].each do |game| %>
						<%= render :partial => "categories/gamelist", :locals => {:game => game} %>
					<% end %>
					</ul>
				<% end %>
			</div>
			<div class="span3">
				<h3>Popular Games</h3>
				<% if @games.any? %>
					<ul class = "popgames">	
					<% @games.sort_by{|g|g.rate_average}.reverse[0..5].each do |game| %>
						<%= render :partial => "categories/gamelist", :locals => {:game => game} %>
					<% end %>
					</ul>
				<% end %>
			</div>
			<div class="span3">
				<h3>Top Players</h3>
				<h3>Site News</h3>
				<h3>Random Game</h3>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<% if current_user.admin? %>
<h2>All Users</h2>
<ul class="userlist">
	<% @users.each do |u| %>
		<li>
			Username = <%= u.username %> | Email = <%= u.email %> | <%= link_to "delete", u, method: :delete %>
		</li>
	<% end %>
</ul>
<% end %>